#!/usr/bin/env python3
"""Check (or regenerate) the memory stores' layout, ledgers, and frontmatter.

Plain `python3`, not the `uv run --script` shebang the rest of this author's
Python carries. A deliberate one-file break with that convention: a consumer of
memkit cannot be assumed to have uv, and this script is the one piece an
adopter may want to run from a git hook or a bare CI image. The floor is still
3.12 — see the version guard below, which exists so an older interpreter says
so by name instead of dying on a syntax error nobody can read.

Tier is PATH, not frontmatter. Each store contains exactly:

    MEMORY.md   hot ledger — auto-loaded every session, hand-curated
    SEARCH.md   search ledger — never loaded, GENERATED by this script
    hot/        hot memories (one MEMORY.md row each)
    search/     retrieval-only memories, incl. domain sub-dirs like
                search/<domain>/ whose INDEX.md ledgers its own subtree
    archive/    dead memories: no tier, no row, not retrieved

A `tier:` frontmatter key is an error: it was the old source of truth and
two sources of truth for the same fact is how they drift. The recall hook
reads the same layout (it roots retrieval at `<store>/search`), so a file's
directory decides whether it is in context already or discoverable by search —
nothing else does.

SEARCH.md and the sub-indexes are generated: `--write` rewrites every row
from the corresponding file's frontmatter `description:`, alphabetically by
label, plus the "(N memories)" counts. Check mode fails on any drift. Hot
rows stay hand-written — a hot row is a judgement about what deserves to be
in context, which no generator can make — but a hot file edited after its
row was last touched draws a staleness warning.

Every markdown link that names a file must resolve on disk (DEAD-LINK), and
every wikilink should name a memory that exists (DANGLING-WIKILINK, a warning
— a dangling one is the store's way of marking a memory worth writing). Repo
paths cited in PROSE must resolve too (DEAD-PATH). Those fail the run only in
the memories the current commit touches, whatever else was read: `--all`
widens the scan to the whole store and reports the rest as warnings, so an
audit still surfaces drift without failing whoever happened to run it.

Which trees to check comes from the config file (`--config`, else
MEMKIT_CONFIG), and for each store it is the EDIT tree — `edit_root`, the tree
whose changes are being verified — not the live copy the recall hook serves.
Run from a worktree, this checks and rewrites that worktree. Exits 0 if all
stores are consistent; 1 otherwise.
"""

from __future__ import annotations

import sys

if sys.version_info < (3, 12):  # noqa: UP036 — the guard IS the old-version path
    # Named, and before anything else runs. The alternative an adopter meets is
    # a SyntaxError from somewhere in the middle of the file, which reads as
    # "this tool is broken" rather than "this tool wants a newer python".
    sys.exit(
        "memory-integrity: needs python 3.12 or newer, found "
        f"{sys.version_info.major}.{sys.version_info.minor}. "
        "(The recall hook holds a 3.9 floor; this checker does not.)"
    )

import argparse  # noqa: E402 — everything below the version guard, by design
import contextlib  # noqa: E402
import os  # noqa: E402
import re  # noqa: E402
import subprocess  # noqa: E402
from pathlib import Path  # noqa: E402

from memkit._exec import (  # noqa: E402
    GitRoute,
    Rev,
    Untrusted,
    run_git,
)
from memkit.memory_prompt_recall import (  # noqa: E402
    CONFIG_ENV,
    ConfigError,
    load_config,
)

# What a branch is measured against when deciding which files it is answerable
# for, when the config names none. Config overrides it (citations.blame_base),
# and fixtures build repos with no remote at all.
DEFAULT_BLAME_BASE = "origin/main"


# The installed console script, which is what a reader of a finding can
# actually type. Not a path: this tool ships as a package entry point, and a
# remediation naming a file that only exists in somebody's checkout is a
# remediation that stops working the moment it is adopted.
#
# Bare, and no qualifier about where you are standing: this run verified the
# tree you are editing (see stores_from_config), so the same command from the
# same directory rewrites the ledgers this run just complained about. The
# recipe carried a config-derived `VAR=$PWD` prefix while the checker verified
# the live tree instead; verifying the edit tree is what removed the need.
WRITE_CLI = "memory-integrity --write"
WRITE_RECIPE = f"run `{WRITE_CLI}`"


def _stale_base_hint(blame_base: str) -> str:
    """Printed under DEAD-PATH errors. A citation this change did not touch can
    only be blamed on it if the merge base is older than it should be, and that
    has one cause worth naming and a one-line remedy."""
    return (
        f"(if a citation above is not yours, {blame_base} may be stale — "
        "`git fetch` and re-run)"
    )


def _store(
    root: Path,
    mem_dir: str,
    sub_indexes: tuple[str, ...] = (),
    *,
    store_id: str = "store",
    link_roots: tuple[Path, ...] = (),
    cited_roots: tuple[str, ...] = (),
    cited_suffixes: tuple[str, ...] = (),
    citations_declared: bool = True,
    blame_base: str = DEFAULT_BLAME_BASE,
) -> dict:
    """One store, fully described — nothing below reads a module-level tree.

    `root` is the ONE tree this pass reads, blames and — under `--write` —
    rewrites: the tree whose changes are being verified. `link_roots` are the
    trees an absolute or `~`-rooted link may point into and still be ours to
    verify, which is a wider set than `root` alone: a memory may link the
    canonical copy of another store by absolute path, while a link to
    /nix/store or /etc is somebody else's filesystem.

    `cited_roots` defaults to EMPTY, and empty means the prose-citation check
    matches nothing. That is a real state — a store in a repo whose top-level
    layout memkit was never told about — and check() reports it rather than
    passing quietly, because a citation check that silently matches nothing is
    the vacuous green this whole file exists to refuse.

    `citations_declared` is the other half of that, and without it the report
    is wrong for the commonest store there is. A config that never mentions
    `citations` has opted OUT of the feature, and a checker that answered a
    fresh adopter's first run with two warnings about a check they never asked
    for is one they will learn to skim. Declared-and-empty keeps the warning;
    never-declared says nothing, because there is nothing to say.
    """
    d = root / mem_dir
    return {
        "id": store_id,
        "dir": d,
        "root": root,
        "mem_dir": mem_dir,
        "hot_ledger": d / "MEMORY.md",
        "search_ledger": d / "SEARCH.md",
        "sub_indexes": tuple(d / s for s in sub_indexes),
        "hot": d / "hot",
        "search": d / "search",
        "archive": d / "archive",
        "link_roots": tuple(link_roots) or (root,),
        "cited_roots": tuple(cited_roots),
        "cited_suffixes": tuple(cited_suffixes),
        "citations_declared": citations_declared,
        "blame_base": blame_base,
    }


def stores_from_config(cfg) -> tuple[tuple[dict, ...], list[str]]:
    """(stores, one report line per store) from a loaded config.

    Rooted at each store's EDIT tree, and the two roots divide the labour by
    what each tool is for. The hook's job is RETRIEVAL, so it serves
    `live_root`: every session gets the canonical memories whatever checkout it
    happens to be standing in. A checker's job is VERIFICATION OF A CHANGE, so
    it has to read the tree that change is in — which is what `edit_root`
    (`git_toplevel` of the cwd, in the reference config) already resolves to
    from inside a worktree, with no prefix and nothing to remember.

    Verifying the live tree instead is the seam this replaced. It printed a
    confident `[OK]` about a tree the operator was not editing, and every
    consumer call site had to redirect the root by hand to get the documented
    behaviour — an env override that must be set everywhere to be correct is a
    default pointing the wrong way.

    The report lines exist because the bug this resolver was written for was
    invisible precisely when the output named no tree: `[OK] docs/memories/
    (139 files)` looks identical whether it inspected your worktree or somebody
    else's checkout, and the only tell was a file count that happened to move
    between two runs. Every store SAYS which tree it verified and by which
    route, and names the live tree as well when the hook is serving a different
    one — the check that just passed says nothing about that copy.
    """
    link_roots = tuple(
        dict.fromkeys(
            Path(cfg.root(name))
            for store in cfg.stores
            for name in (store.live_root, store.edit_root)
        )
    )
    built: list[dict] = []
    notes: list[str] = []
    for store in cfg.stores:
        root, how = cfg.root_with_source(store.edit_root)
        live_root, live_how = cfg.root_with_source(store.live_root)
        built.append(
            _store(
                Path(root),
                store.dir,
                store.sub_indexes,
                store_id=store.id,
                link_roots=link_roots,
                cited_roots=cfg.cited_roots,
                cited_suffixes=cfg.extra_suffixes,
                citations_declared=cfg.citations_declared,
                blame_base=cfg.blame_base,
            )
        )
        note = f"{store.id} store: verified in {root}  ({how})"
        if live_root != root:
            note += f"; the hook serves {live_root} ({live_how})"
        notes.append(note)
    return tuple(built), notes


# Auto-memory loader truncates around 24.4KB; warn early so adds don't push past it.
FAIL_BYTES = 24_400
WARN_BYTES = 22_000

# Soft per-row cap for the HOT ledger. Rows are one-line pointers.
LONG_ROW_CHARS = 300

# The recall hook truncates a description at 157 chars, so anything past that
# reaches no reader — not the model, not the ledger skimmer. 155 leaves the
# ellipsis out of it. The long form belongs in the file body.
MAX_DESC_CHARS = 155

LINK_RE = re.compile(r"\(([^)]+\.md)\)")
ROW_RE = re.compile(r"^- \[[^\]]+\]\([^)]+\.md\)")
TIER_RE = re.compile(r"^tier:\s*\S+", re.MULTILINE)
COUNT_RE = re.compile(r"\((\d+) memories")
INDEX_HEADING = "## Index"

# The two ledgers that live at a store ROOT, and the sub-index name that may
# appear anywhere under search/. One definition: the stray-file check, the
# memory-name index and the analyzers all have to agree on what is a ledger
# and what is a memory, and they used to say it three times.
ROOT_LEDGERS = ("MEMORY.md", "SEARCH.md")
SUB_INDEX_NAME = "INDEX.md"
LEDGER_NAMES = {*ROOT_LEDGERS, SUB_INDEX_NAME}
# Directories a memory may live in, relative to the store root. Anything else
# under the store is a file nothing checks — see STRAY-DIR.
TIER_DIRS = ("hot", "search", "archive")

# YAML plain scalars may not START with an indicator character, and may not
# CONTAIN ": " or " #" (which open a mapping or a comment). Everything the
# stores got wrong was one of those: a bare `foo: bar` description, or one
# opening with a backtick.
_YAML_INDICATORS = set("-?:,[]{}#&*!|>%@`")


def _frontmatter(path: Path) -> dict[str, str]:
    """Top-level scalar keys of the leading `---` block, values RAW (unparsed).

    Deliberately not a YAML parser: the raw text is what the description
    checks below need to judge, and adding a dependency to a script that
    gates every commit is a worse trade than 15 lines of line-splitting.
    """
    text = path.read_text(errors="replace")
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    block = text[3 : end if end != -1 else len(text)]
    out: dict[str, str] = {}
    for line in block.splitlines():
        if not line or line[0].isspace() or line.startswith("#"):
            continue  # nested keys (legacy `metadata:`) are not top-level
        key, sep, val = line.partition(":")
        if sep and key.strip() and " " not in key.strip():
            out.setdefault(key.strip(), val.strip())
    return out


def _scalar(raw: str) -> tuple[str | None, str | None]:
    """(value, error) for one raw frontmatter value read as a YAML scalar."""
    if not raw:
        return None, "empty"
    if raw[0] in "\"'":
        quote = raw[0]
        if len(raw) < 2 or raw[-1] != quote:
            return None, f"opens with {quote} and never closes"
        inner = raw[1:-1]
        if quote == "'":
            return inner.replace("''", "'"), None
        if re.search(r'(?<!\\)"', inner):
            return None, "unescaped quote inside a double-quoted scalar"
        return inner.replace('\\"', '"'), None
    if raw[0] in _YAML_INDICATORS:
        return None, f"plain scalar starts with the YAML indicator {raw[0]!r}"
    if ": " in raw or raw.endswith(":"):
        return None, "plain scalar contains ': ' — quote it"
    if " #" in raw:
        return None, "plain scalar contains ' #' — quote it"
    return raw, None


# --- links -------------------------------------------------------------------
#
# A dead link is the failure mode ledger checks cannot see: rows are generated
# from the files they point at, so they are always right, while the pointers
# INSIDE memory prose rot silently every time a doc is renamed. Several links
# into docs/plans/ sat broken for months.
#
# The whole difficulty is telling a link from a piece of quoted text that looks
# like one. Both shapes below are real store content, and both are code:
#
#     `^\d+[hd](?:_[a-z_]+)?$`          a regex — [hd](?:...) parses as a link
#     `![alt](pic.png){width=6.5in}`    a pandoc example — a bare filename
#
# so masking code spans and fenced blocks is not a nicety, it IS the check.
# Indented (4-space) code blocks are NOT masked: in these stores that shape is
# almost always a list continuation carrying real links.

MD_LINK_RE = re.compile(r"!?\[(?P<text>[^\[\]\n]*)\]\((?P<dest>[^)\n]*)\)")
# Wikilinks are memory slugs: no spaces, which is also what keeps `[[ -f x ]]`
# out. `[[:space:]]` is excluded by requiring the name to start alphanumeric.
WIKILINK_RE = re.compile(r"\[\[(?P<name>[A-Za-z0-9][\w./-]*)(?:\|[^\]\n]*)?\]\]")
FENCE_RE = re.compile(r"^\s{0,3}(`{3,}|~{3,})")
TICKS_RE = re.compile(r"`+")
SCHEME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9+.-]*:")
# A destination is a file path if it says so — a slash, or an extension we
# would recognise in this repo. Anything else (`#anchor`, `?q=1`, a word) is
# left alone rather than guessed at.
PATH_SUFFIXES = (
    ".md",
    ".py",
    ".sh",
    ".nix",
    ".json",
    ".yaml",
    ".yml",
    ".toml",
    ".txt",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".webp",
)


def _mask_spans(line: str) -> str:
    """`line` with inline code spans blanked, columns preserved.

    CommonMark rule: a run of N backticks opens a span that the next run of
    exactly N closes. An unmatched run is literal text.
    """
    chars = list(line)
    runs = [(m.start(), m.end()) for m in TICKS_RE.finditer(line)]
    i = 0
    while i < len(runs):
        start, end = runs[i]
        for j in range(i + 1, len(runs)):
            if runs[j][1] - runs[j][0] == end - start:
                for k in range(start, runs[j][1]):
                    chars[k] = " "
                i = j
                break
        i += 1
    return "".join(chars)


def _indent_columns(line: str) -> int:
    """Leading whitespace measured in COLUMNS, tabs advancing to a stop of 4.

    CommonMark lays tabs on a four-column grid, so a tab preceded by one, two
    or three spaces still reaches column 4 and opens an indented code block.
    Matching the literal `    ` or a leading tab missed those three forms, and
    what escapes the mask in a transcript is a path the author only quoted —
    reported as a broken citation against the commit that quoted it.
    """
    col = 0
    for ch in line:
        if ch == " ":
            col += 1
        elif ch == "\t":
            col += 4 - (col % 4)
        else:
            break
        if col >= 4:
            break
    return col


def _mask_code(text: str, mask_indented: bool = False) -> list[str]:
    """Lines of `text` with all code blanked out, one entry per source line."""
    return _mask_and_fence(text, mask_indented)[0]


def _mask_and_fence(text: str, mask_indented: bool = False) -> tuple[list[str], int]:
    """(masked lines, line number of a fence that is never closed — 0 if none).

    The second value is the checker's own blind spot made visible: an
    unterminated fence masks every line after it, so a memory with one gets a
    silent pass from the link and citation checks. Nothing else can notice —
    the masked text is indistinguishable from a file with no links at all.

    `mask_indented` also blanks CommonMark indented code blocks (4 spaces or a
    tab, opening after a blank line). The two callers deliberately differ, and
    the asymmetry is not an oversight:

      links (False)      an indented run in these stores is nearly always a
                         list continuation carrying real pointers, and a dead
                         link is worth a false positive to catch.
      citations (True)   the same run is nearly always a transcript or a
                         sample command, whose paths belong to some other tree
                         or to no tree at all. Citations BLOCK on files the
                         commit touched, so a false positive there fails an
                         author for a path they only quoted.
    """
    out: list[str] = []
    fence: str | None = None
    opened = 0
    prev_blank = True  # start of document opens an indented block, same as CM
    indented = False
    for lineno, line in enumerate(text.splitlines(), 1):
        m = FENCE_RE.match(line)
        blank = not line.strip()
        if fence is not None:
            out.append("")
            # A closing fence is the same character, at least as long, and
            # carries no info string.
            if (
                m
                and m.group(1)[0] == fence[0]
                and len(m.group(1)) >= len(fence)
                and not line.strip().strip(fence[0])
            ):
                fence = None
                # A fenced block ends whatever came before it, so the next line
                # starts a fresh block — an indented run directly after the
                # closing fence opens code exactly as one after a blank line
                # does, and treating it as a paragraph continuation left it
                # unmasked.
                prev_blank = True
            continue
        if m:
            fence = m.group(1)
            opened = lineno
            out.append("")
            prev_blank = False
            continue
        if mask_indented:
            # A blank line does not end an indented block; the next flush line
            # does. Matches CommonMark, and matters here because sample output
            # routinely has blank lines in the middle of it.
            if indented and (blank or _indent_columns(line) >= 4):
                out.append("")
                prev_blank = blank
                continue
            indented = prev_blank and not blank and _indent_columns(line) >= 4
            if indented:
                out.append("")
                prev_blank = False
                continue
        out.append(_mask_spans(line))
        prev_blank = blank
    return out, opened if fence is not None else 0


def _dest(raw: str) -> str:
    """The URL of a link destination: first token, `<>` and title stripped."""
    return raw.strip().split()[0].strip("<>") if raw.strip() else ""


def _link_path(dest: str, source: Path, roots: tuple[Path, ...]) -> Path | None:
    """Absolute path a destination names, or None if it is not ours to check.

    Skipped: external schemes (`https:`, `mailto:`), bare anchors, anything
    that does not look like a path, and absolute paths outside `roots`.
    """
    target = dest.split("#", 1)[0].strip()
    if not target or SCHEME_RE.match(target):
        return None
    if "/" not in target and not target.lower().endswith(PATH_SUFFIXES):
        return None
    p = Path(target).expanduser()
    if not p.is_absolute():
        return source.parent / p
    resolved = p.resolve()
    return resolved if any(_within(resolved, r) for r in roots) else None


def _within(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root.resolve())
    except ValueError:
        return False
    return True


def _memory_names(stores: tuple[dict, ...]) -> set[str]:
    """Every name a wikilink may resolve to, across ALL stores and all tiers.

    Filename stem and frontmatter `name:` both count, and archive/ counts too:
    a wikilink to an archived memory is a stale pointer, not a dangling one,
    and the ARCHIVED-ROW check already owns that story.
    """
    names: set[str] = set()
    for store in stores:
        d = store["dir"]
        if not d.is_dir():
            continue
        for p in d.rglob("*.md"):
            if p.name in LEDGER_NAMES:
                continue
            names.add(p.stem)
            value, _ = _scalar(_frontmatter(p).get("name", ""))
            if value:
                names.add(value)
    return names


def _check_links(store: dict, names: set[str]) -> tuple[list[str], list[str]]:
    """Dead file links (errors) and dangling wikilinks (warnings) in a store.

    Every .md in the store is read, ledgers and archive included: a generated
    ledger's rows are trustworthy, but its hand-written preamble is not.
    """
    errors: list[str] = []
    warnings: list[str] = []
    d = store["dir"]
    rel_dir = d.relative_to(store["root"])
    roots = (store["root"], *store["link_roots"])
    for p in sorted(d.rglob("*.md")):
        where = f"{rel_dir}/{p.relative_to(d)}"
        lines, unclosed = _mask_and_fence(p.read_text(errors="replace"))
        if unclosed:
            errors.append(
                f"UNCLOSED-FENCE: {where}:{unclosed} — code fence opened here "
                "is never closed, so every line below it is masked out of the "
                "link and citation checks"
            )
        for n, line in enumerate(lines, 1):
            for m in MD_LINK_RE.finditer(line):
                dest = _dest(m.group("dest"))
                target = _link_path(dest, p, roots)
                if target is None or target.exists():
                    continue
                errors.append(
                    f"DEAD-LINK: {where}:{n} — [{m.group('text')}]({dest}) "
                    "points at no file"
                )
            for m in WIKILINK_RE.finditer(line):
                name = m.group("name")
                if name.removesuffix(".md") not in names:
                    warnings.append(
                        f"DANGLING-WIKILINK: {where}:{n} — [[{name}]] names no "
                        "memory (fine if it marks one worth writing)"
                    )
    return errors, warnings


# --- cited paths -------------------------------------------------------------
#
# Memories cite repo paths in PROSE far more often than they link them:
# "the host list is modules/example/hosts.nix", "the alias lives in
# users/example/host.nix:1470". Those rot exactly like links do, and until
# now nothing looked at them — a memory can name a module that was renamed a
# year ago and every check stays green.
#
# Only memories the CURRENT COMMIT touches can FAIL the run. Drift in a file
# the commit never opened is somebody else's rot, and a check that fails on rot
# you did not cause is a check that gets switched off — taking the citations
# you DID break with it. `--all` (or MEMORY_INTEGRITY_ALL_CITATIONS=1) widens
# what is read to the whole store and reports the surplus as warnings; the
# blame line does not move.
#
# Code spans and fences are masked, same as the link check, and that is most
# of what this check does NOT see: house style backticks paths, so a full-store
# audit of the author's stores matches 35 citations in prose (all resolving)
# against 481 inside backticks. Unmasking is still wrong — 45 of those 481
# resolve nowhere, and nearly every one is ANOTHER repo's path quoted inside a
# memory about that repo. Nothing in the text says which repo a backticked
# path belongs to, so
# unmasking buys ~45 false positives to catch nothing. Narrow and quiet beats
# broad and ignored.


def _cited_path_re(cited_roots: tuple[str, ...]):
    """Regex matching a prose path into one of the repo's own top-level trees.

    A citation into anything else (/etc/hosts, src/foo.py in some other
    project) is not ours to resolve, so it is not matched at all. No configured
    roots means no regex at all, rather than one that matches everything.

    The lookbehind is what keeps URLs and longer paths out: in
    `https://github.com/o/r/blob/master/modules/x.nix` the word `modules` is
    preceded by `/`, so nothing matches. `:` and `~` are outside the character
    class, so a line-number suffix (`host.nix:1470`, `flake.nix~2530`) simply
    ends the match — the path part is checked and the suffix is never part of
    it.
    """
    if not cited_roots:
        return None
    return re.compile(
        r"(?<![\w./~-])(?:"
        + "|".join(re.escape(root) for root in cited_roots)
        + r")/[\w./+-]*"
    )


def _cited_path(token: str, suffixes: tuple[str, ...]) -> str | None:
    """The repo-relative path a prose token names, or None if it names none.

    Trailing `.` and `-` are prose, not filename: "see modules/foo.nix." ends
    a sentence. A token counts as a citation only if it carries a known
    extension or a trailing `/` (a directory) — `docs/plans` alone reads as a
    topic, `docs/plans/` as a place.
    """
    token = token.rstrip(".-")
    if token.endswith("/") or token.lower().endswith(suffixes):
        return token
    return None


def _changed_files(repo: Path, blame_base: str) -> tuple[set[str], str]:
    """(repo-relative paths this commit touches, why git could not say).

    EXACT semantics: `git diff --name-only HEAD` — staged AND unstaged changes
    against the last commit, deletions included (a deleted file is simply not
    on disk to read) — plus `git ls-files --others --exclude-standard` for
    files that are new and not ignored, plus everything the commits already on
    this branch touched (`merge-base <blame_base> HEAD`..HEAD). Always answers
    that one question: `--all` widens what gets READ, never who is answerable,
    so it is the caller's business and no longer this function's.

    The branch's own commits belong in the set because committing is not
    verifying: with the working tree alone, an author who broke a citation and
    committed it before running the check had it reclassified as world drift —
    a warning about somebody else's rot — precisely because they had committed
    it. The check would then pass on the change that broke it. A branch is the
    unit a PR is answerable for, so that is the unit blamed.

    Paths come back NUL-delimited: git QUOTES a path containing non-ASCII or a
    newline when it writes one per line, and a quoted path matches no memory
    file, so the file drops out of the blamed set silently.

    Degrades to the EMPTY set — check nothing — when git is missing, when
    `repo` is not the toplevel of a repository (fixture stores under a
    tmpdir), or when there is no HEAD yet. Checking everything would be the
    other option, but a fresh clone with no HEAD, or a tmpdir fixture, would
    then report the whole store's accumulated drift as if this run caused it.
    The second element always says why the answer is what it is, and check()
    reports it either way: a degrade and a clean tree both mean "no citation
    was looked at", and the two used to be equally silent. A run that checks
    nothing has to SAY it checks nothing, or the check is indistinguishable
    from a check that passed.
    """

    def git(route: GitRoute, **holes) -> subprocess.CompletedProcess[str] | None:
        try:
            out = run_git(route, repo=str(repo), timeout=30, **holes)
        except (OSError, subprocess.SubprocessError, Untrusted):
            return None
        return out if out.returncode == 0 else None

    def paths(proc: subprocess.CompletedProcess[str] | None) -> list[str]:
        return [n for n in proc.stdout.split("\0") if n] if proc else []

    top = git(GitRoute.TOPLEVEL)
    if top is None or Path(top.stdout.strip()).resolve() != repo.resolve():
        return set(), f"{repo} is not a git toplevel"
    changed = git(GitRoute.CHANGED_VS_HEAD)
    if changed is None:
        return set(), "no HEAD to diff against"
    names = paths(changed) + paths(git(GitRoute.UNTRACKED))
    # A branch with no merge base — blame_base unfetched, a repo without that
    # ref at all, a fixture — simply contributes nothing here. The working tree
    # still answers, so the check degrades to what it did before rather than to
    # nothing. A STALE blame_base fails the other way: the merge base sits
    # further back than it should, so commits already on main land in the
    # blamed set and somebody else's drift blocks this build. No fetch is done
    # to prevent that — network in a gate that runs on every commit costs more
    # than the fault — so the DEAD-PATH text names it instead.
    # A `blame_base` that is not a revision refuses AT CONSTRUCTION, so there
    # is no empty argument for git to fail on for an incidental reason and no
    # second call site to disagree about what a refusal meant.
    base = None
    with contextlib.suppress(Untrusted):
        base = git(GitRoute.MERGE_BASE, rev=Rev(blame_base))
    if base is not None and base.stdout.strip():
        with contextlib.suppress(Untrusted):
            names += paths(
                git(GitRoute.CHANGED_SINCE, rev=Rev(base.stdout.strip()))
            )
    files = set(names)
    return files, "" if files else "working tree is clean and no commits on this branch"


def _read_any(store: dict, changed: set[str] | None) -> bool:
    """Whether the citation scan would open at least one memory of this store.

    Deliberately the same predicate _check_cited_paths filters on, files on
    disk included: a DELETED memory is in the changed set but has nothing to
    read, so counting it would claim a check that never happened.
    """
    if changed is None:
        return True
    root = store["root"]
    return any(
        p.relative_to(root).as_posix() in changed for p in store["dir"].rglob("*.md")
    )


def _check_cited_paths(store: dict, scan: set[str] | None) -> list[tuple[str, str]]:
    """(citing file, finding) for prose citations that name no file.

    `scan` is which memories to READ — None for every one of them. The citing
    file comes back with each finding because reading and blaming are two
    different questions: under --all this reads the whole store, and only the
    caller knows which of those files the current commit is answerable for.

    Markdown link destinations are skipped: DEAD-LINK already owns them, and
    it resolves them relative to the citing FILE rather than the repo root, so
    reporting them here would both double up and disagree.
    """
    if scan is not None and not scan:
        return []
    cited_re = _cited_path_re(store["cited_roots"])
    if cited_re is None:
        return []
    # Extensions that make a token a file citation: the link checker's set plus
    # whatever else this repo cites in prose but never links.
    # Bound with a type, like `search_ledger` below and for the same reason:
    # `store` is a plain dict, so reading it yields Unknown, and unpacking that
    # into a tuple literal gives one whose tail no longer matches the
    # `tuple[str, ...]` the callee declares.
    configured: tuple[str, ...] = tuple(store["cited_suffixes"])
    suffixes = (*PATH_SUFFIXES, *configured)
    found: list[tuple[str, str]] = []
    d = store["dir"]
    root = store["root"]
    rel_dir = d.relative_to(root)
    for p in sorted(d.rglob("*.md")):
        rel = p.relative_to(root).as_posix()
        if scan is not None and rel not in scan:
            continue
        where = f"{rel_dir}/{p.relative_to(d)}"
        for n, line in enumerate(
            _mask_code(p.read_text(errors="replace"), mask_indented=True), 1
        ):
            dests = [m.span("dest") for m in MD_LINK_RE.finditer(line)]
            for m in cited_re.finditer(line):
                if any(start <= m.start() < end for start, end in dests):
                    continue
                cited = _cited_path(m.group(0), suffixes)
                if cited is None or (root / cited).exists():
                    continue
                found.append((rel, f"DEAD-PATH: {where}:{n} — {cited} names no file"))
    return found


def _row(label: str, link: str, desc: str) -> str:
    return f"- [{label}]({link}) — {desc}"


def _rows(ledger: Path, store_dir: Path) -> dict[str, Path]:
    """{store-relative path -> ledger} for every memory file a ledger rows.

    Links resolve against the LEDGER's own directory (`../foo.md` from a
    sub-index is the same file as `search/foo.md` from SEARCH.md) and are
    kept only if they land inside the store. Ledgers themselves excluded.
    """
    if not ledger.is_file():
        return {}
    out: dict[str, Path] = {}
    for n in LINK_RE.findall(ledger.read_text()):
        if "://" in n:
            continue
        target = (ledger.parent / n).resolve()
        if target.name in LEDGER_NAMES:
            continue
        try:
            rel = target.relative_to(store_dir.resolve())
        except ValueError:
            continue  # ../plans/x.md and friends
        out[str(rel)] = ledger
    return out


def _rows_at(
    ledger: Path, store_dir: Path, repo: Path, base: str
) -> dict | None:
    """The rows a ledger carried at `base`, or None when that cannot be read.

    None rather than an empty dict, and the difference is the whole safety of
    the finding built on this: a repo with no such ref, no git at all, or a
    ledger that did not exist then all produce "no rows", and treating that as
    "every row was lost" would fail every fresh checkout.
    """
    try:
        rel = ledger.resolve().relative_to(repo.resolve())
    except ValueError:
        return None
    try:
        out = run_git(
            GitRoute.BLOB_AT, repo=str(repo), rev=Rev(base), path=str(rel)
        )
    except (OSError, subprocess.SubprocessError, Untrusted):
        return None
    if out.returncode != 0:
        return None
    found: dict = {}
    for link in LINK_RE.findall(out.stdout):
        if "://" in link:
            continue
        target = (ledger.parent / link).resolve()
        if target.name in LEDGER_NAMES:
            continue
        try:
            found[str(target.relative_to(store_dir.resolve()))] = ledger
        except ValueError:
            continue
    return found


def _row_lost(store: dict, write: bool) -> list:
    """Rows a MACHINE WRITE took away, named so the loss is not silent.

    `SEARCH.md` is generated, and a generated ledger is a file a tool rewrites
    wholesale. That is fine while every live memory produces a row; when one
    stops — a description that became unreadable, a memory moved under a
    directory that is not a tier — the rewrite drops its row and the memory
    goes on existing, retrievable by the hook and invisible to every ledger
    anybody reads.

    THE CARVE-OUT, and it is what makes this a real finding rather than noise:
    a row whose memory is no longer on disk is not lost, it was deleted, and
    that is an author doing their job. Only a row that had a file at the base
    and still has one now can have been taken by a machine.

    `--write` DOES NOT RESOLVE IT. Every other ledger finding is drift a
    rewrite settles, and this one is evidence a rewrite erases: regenerating
    the ledger either puts the row back or leaves it out, and either way the
    fact that a row went missing is gone. That is the agent-access posture
    applied to the checker's own repair path — a tool may fix what it can
    describe, and may not make what it cannot describe disappear.
    """
    del write  # deliberately unused; see the docstring
    ledger = store["search_ledger"]
    base = store["blame_base"]
    at_base = _rows_at(ledger, store["dir"], store["root"], base)
    if at_base is None:
        return []
    # EVERY ledger a search-tier memory may legitimately be rowed in, as
    # found. Reading only `SEARCH.md` on both sides made the documented
    # "start a new domain" move — hand-seed one row in a sub-index, then
    # `--write` — read as a row a machine took away; and since `--write`
    # deliberately does not settle this finding, the operator was left with no
    # move at all, the push blocked until the sub-index change was reverted.
    #
    # As FOUND rather than from the caller's earlier scan, which is what makes
    # the call's POSITION load-bearing: after the rewrite below the row is
    # back, and this finding would report nothing — precisely the erasure it
    # exists to describe.
    current: dict = {}
    for owner in (ledger, *store["sub_indexes"]):
        current.update(_rows(owner, store["dir"]))
    lost = []
    for rel in sorted(at_base):
        if rel in current:
            continue
        if not (store["dir"] / rel).is_file():
            # Deleted, not lost. An author removing a memory is the ledger
            # working.
            continue
        lost.append(
            f"ROW-LOST: {store['dir'].name}/{rel} had a row at {base} and has "
            "none now, and the file is still there. A generated ledger is "
            "rewritten wholesale, so a memory that stops producing a row goes "
            "on existing with nothing pointing at it. --write does not settle "
            "this: regenerating the ledger erases the evidence rather than the "
            "cause."
        )
    return lost


def _live(store: dict) -> list[Path]:
    """Every live memory file, hot and search, sorted."""
    files: list[Path] = []
    for base in (store["hot"], store["search"]):
        if base.is_dir():
            files += [p for p in base.rglob("*.md") if p.name not in LEDGER_NAMES]
    return sorted(files)


def _sub_members(store: dict) -> dict[str, Path]:
    """Which sub-index each search file belongs to. Membership is DATA —
    read from the sub-index's existing rows — not convention: moving a
    memory into a domain index means moving its row once, by hand, after
    which --write maintains it. Anything unclaimed lands in SEARCH.md."""
    out: dict[str, Path] = {}
    for sub in store["sub_indexes"]:
        for rel in _rows(sub, store["dir"]):
            out.setdefault(rel, sub)
    return out


def _generate(ledger: Path, entries: list[tuple[str, str, str]]) -> str:
    """Ledger text: the file's own preamble through `## Index`, then rows."""
    old = ledger.read_text() if ledger.is_file() else f"{INDEX_HEADING}\n"
    head, sep, _ = old.partition(INDEX_HEADING)
    preamble = (head + sep) if sep else old.rstrip("\n") + f"\n\n{INDEX_HEADING}"
    body = "\n".join(_row(*e) for e in sorted(entries, key=lambda e: e[0].lower()))
    return f"{preamble}\n\n{body}\n"


def _last_touch(repo: Path, paths: list[str]) -> dict[str, int]:
    """path -> unix time of the newest commit touching it (0 if untracked)."""
    if not paths:
        return {}
    try:
        out = run_git(
            GitRoute.LAST_TOUCH, repo=str(repo), paths=list(paths), timeout=60
        )
    except (OSError, subprocess.SubprocessError, Untrusted):
        return {}
    seen: dict[str, int] = {}
    ts = 0
    for line in out.stdout.splitlines():
        if line.isdigit():
            ts = int(line)
        elif line.strip():
            seen.setdefault(line.strip(), ts)
    return seen


def _row_touch(repo: Path, ledger: Path, limit: int = 400) -> dict[str, int]:
    """basename -> unix time of the newest commit whose diff to `ledger`
    mentioned it. One `git log -p` walk; the pickaxe alternative is one
    process per row."""
    try:
        rel = str(ledger.relative_to(repo))
    except ValueError:
        return {}
    try:
        out = run_git(
            GitRoute.ROW_TOUCH, repo=str(repo), limit=limit, path=rel, timeout=60
        )
    except (OSError, subprocess.SubprocessError, Untrusted):
        return {}
    seen: dict[str, int] = {}
    ts = 0
    for line in out.stdout.splitlines():
        if line.isdigit():
            ts = int(line)
        elif line[:1] in "+-" and line[1:2] not in "+-":
            for name in LINK_RE.findall(line):
                seen.setdefault(os.path.basename(name), ts)
    return seen


def check(
    store: dict,
    write: bool,
    names: set[str] | None = None,
    all_citations: bool = False,
) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    d = store["dir"]
    # Relative to the STORE's own root, not a single global REPO — two stores
    # in one config can and do resolve to different trees.
    rel_dir = d.relative_to(store["root"])

    if not d.is_dir():
        return [f"ERROR: directory not found: {d}"], []
    for ledger in (store["hot_ledger"], store["search_ledger"]):
        if not ledger.is_file():
            return [f"ERROR: ledger not found: {ledger}"], []
    if not store["hot"].is_dir() or not store["search"].is_dir():
        return [
            f"NOT-MIGRATED: {rel_dir} has no hot/ + search/ split. Tier is "
            "path-based now; move each file into hot/ or search/ and drop its "
            "`tier:` frontmatter."
        ], []

    # A .md the tier layout does not account for is checked by NOTHING: it is
    # outside _live (so no frontmatter, description or ledger row is required
    # of it) and outside every tier the hook searches, so it is a memory that
    # exists and can never be retrieved. Two shapes: loose at the store root
    # (somebody wrote it the old way), or under a directory that is not a
    # tier — `notes/`, `drafts/`, a half-finished domain folder. The root case
    # was caught; the second was the gap.
    for p in sorted(d.rglob("*.md")):
        rel = p.relative_to(d)
        if len(rel.parts) == 1:
            if p.name not in ROOT_LEDGERS:
                errors.append(
                    f"STRAY-ROOT: {rel_dir}/{p.name} — memories live in hot/ or search/"
                )
        elif rel.parts[0] not in TIER_DIRS:
            errors.append(
                f"STRAY-DIR: {rel_dir}/{rel} — {rel.parts[0]}/ is not a tier "
                f"({'/, '.join(TIER_DIRS)}/), so nothing checks or retrieves it"
            )

    hot_text = store["hot_ledger"].read_text()
    size = len(hot_text.encode("utf-8"))
    if size > FAIL_BYTES:
        errors.append(f"OVER-CAP: {rel_dir}/MEMORY.md is {size}b (cap {FAIL_BYTES})")
    elif size > WARN_BYTES:
        warnings.append(f"NEAR-CAP: {rel_dir}/MEMORY.md is {size}b (warn {WARN_BYTES})")
    warnings.extend(
        f"LONG-ROW ({len(line)}c): {line[:80]}..."
        for line in hot_text.splitlines()
        if ROW_RE.match(line) and len(line) > LONG_ROW_CHARS
    )

    rowed: dict[str, Path] = {}
    for ledger in (store["hot_ledger"], store["search_ledger"], *store["sub_indexes"]):
        if ledger in store["sub_indexes"] and not ledger.is_file():
            errors.append(f"ERROR: sub-index not found: {ledger}")
            continue
        for rel, owner in _rows(ledger, d).items():
            if rel in rowed:
                # A clash between two GENERATED ledgers is settled by the
                # rewrite below, so reporting it would fail the very run that
                # fixes it — that is the normal state of a memory moving into
                # or out of a sub-index. At most one of the two owners can be
                # the hand-written MEMORY.md, and the one clash the rewrite
                # cannot settle (a search-tier file rowed there) is reported
                # as MISROWED, which names the edit to make.
                if not write:
                    errors.append(
                        f"DOUBLE-LEDGER: {rel_dir}/{rel} rowed in "
                        f"{rowed[rel].name} and {owner.name}"
                    )
                continue
            rowed[rel] = owner

    generated: dict[Path, list[tuple[str, str, str]]] = {
        ledger: [] for ledger in (store["search_ledger"], *store["sub_indexes"])
    }
    sub_members = _sub_members(store)
    # Bound once with a type: `store` is a plain dict, so indexing it yields
    # Unknown, and an Unknown default makes dict.get resolve to its
    # returns-None overload.
    search_ledger: Path = store["search_ledger"]
    live = _live(store)
    for p in live:
        rel = str(p.relative_to(d))
        fm = _frontmatter(p)
        if TIER_RE.search(p.read_text(errors="replace")[:4096]):
            errors.append(f"TIER-KEY: {rel_dir}/{rel} — tier is the directory now")
        desc, why = _scalar(fm.get("description", ""))
        if desc is None:
            errors.append(f"DESC-BAD: {rel_dir}/{rel} — description {why}")
        elif len(desc) > MAX_DESC_CHARS:
            errors.append(
                f"DESC-LONG: {rel_dir}/{rel} — {len(desc)}c "
                f"(max {MAX_DESC_CHARS}; the hook truncates at 157)"
            )
        is_hot = store["hot"] in p.parents
        owner = rowed.get(rel)
        if owner is None:
            # A search file's row is generated, so under --write it is about to
            # exist and reporting it missing would fail the very run that fixes
            # it. `rowed` is read before generation and deliberately not
            # refreshed: the whole point is to describe the tree as found.
            if not (write and not is_hot):
                errors.append(
                    f"ORPHAN: {rel_dir}/{rel} — no row in "
                    + ("MEMORY.md" if is_hot else "SEARCH.md")
                )
        elif is_hot and owner != store["hot_ledger"]:
            errors.append(f"MISROWED: {rel_dir}/{rel} is hot but rowed in {owner.name}")
        elif not is_hot and owner == store["hot_ledger"]:
            errors.append(
                f"MISROWED: {rel_dir}/{rel} is search-tier but rowed in MEMORY.md"
            )
        if not is_hot and desc is not None:
            ledger = sub_members.get(rel, search_ledger)
            link = os.path.relpath(p, ledger.parent)
            generated[ledger].append((fm.get("name") or p.stem, link, desc))

    # Under --write, a bad row in a GENERATED ledger is not a finding: the
    # rewrite below drops it. Only rows in MEMORY.md, which stays hand-written,
    # can survive the run and so deserve to fail it.
    def _survives(owner: Path) -> bool:
        return not write or owner == store["hot_ledger"]

    # BEFORE the generated ledgers are rewritten below, because after them the
    # question cannot be asked: `--write` is about to make the ledger agree
    # with the tree, and what this reports is a row that stopped agreeing.
    errors.extend(_row_lost(store, write))

    on_disk = {str(p.relative_to(d)) for p in live}
    errors.extend(
        f"STALE: {rel_dir}/{owner.name} rows missing {rel}"
        for rel, owner in sorted(rowed.items())
        if rel not in on_disk and _survives(owner)
    )

    arch = store["archive"]
    if arch.is_dir():
        errors.extend(
            f"ARCHIVED-ROW: {rel_dir}/archive/{p.name} still has a ledger row"
            for p in sorted(arch.glob("*.md"))
            if f"archive/{p.name}" in rowed and _survives(rowed[f"archive/{p.name}"])
        )

    # Generated ledgers: rewrite under --write, report drift otherwise.
    counts: dict[Path, int] = {}
    for ledger, entries in generated.items():
        if not ledger.is_file():
            # No count for a ledger that is not there. Recording one would let
            # the MEMORY.md rewrite below edit the row to "(0 memories)" —
            # erasing the real number while the run errors about the missing
            # file, so --write would silently make the damage harder to see.
            continue
        counts[ledger] = len(entries)
        want_text = _generate(ledger, entries)
        if ledger.read_text() == want_text:
            continue
        if write:
            ledger.write_text(want_text)
        else:
            errors.append(
                f"LEDGER-DRIFT: {rel_dir}/{ledger.relative_to(d)} is generated "
                f"from frontmatter — {WRITE_RECIPE}"
            )

    # "(N memories)" counts on the MEMORY.md rows that point at each ledger.
    # Matched by resolving the row's own link, not by filename: two stores
    # and every sub-index all end in INDEX.md or SEARCH.md.
    def _links_to(line: str, target: Path) -> bool:
        return any(
            (store["hot_ledger"].parent / n).resolve() == target.resolve()
            for n in LINK_RE.findall(line)
            if "://" not in n
        )

    new_hot = []
    for line in hot_text.splitlines(keepends=True):
        for ledger, n in counts.items():
            if _links_to(line, ledger):
                line = COUNT_RE.sub(f"({n} memories", line, count=1)
        new_hot.append(line)
    fixed_hot = "".join(new_hot)
    if fixed_hot != hot_text:
        if write:
            store["hot_ledger"].write_text(fixed_hot)
        else:
            errors.append(
                f"COUNT-DRIFT: {rel_dir}/MEMORY.md ledger counts are stale — "
                f"{WRITE_RECIPE}"
            )

    # Hot rows are hand-written, so nothing keeps them honest when the file
    # they describe is rewritten. Warning, not error: a row can be correct
    # and older than the edit that prompted it.
    hot_files = [p for p in live if store["hot"] in p.parents]
    touched = _last_touch(
        store["root"], [str(p.relative_to(store["root"])) for p in hot_files]
    )
    row_ts = _row_touch(store["root"], store["hot_ledger"])
    for p in hot_files:
        f_ts = touched.get(str(p.relative_to(store["root"])), 0)
        r_ts = row_ts.get(p.name, 0)
        if f_ts and r_ts and f_ts > r_ts:
            days = (f_ts - r_ts) // 86_400
            warnings.append(
                f"HOT-STALE: {rel_dir}/{p.relative_to(d)} was edited "
                f"{days}d after its MEMORY.md row — re-read the row"
            )

    # Last, so it reads the tree as this run LEAVES it: under --write the
    # generated ledgers above have already been rewritten, and reporting a
    # dead row link that the same run just deleted would fail the run that
    # fixed it. Nothing here is fixed by --write, so the two modes otherwise
    # report identically.
    link_errors, link_warnings = _check_links(
        store, _memory_names((store,)) if names is None else names
    )
    errors += link_errors
    warnings += link_warnings

    # Reading and blaming are separate questions, and answering them with one
    # set made --all — the mode check-all runs, i.e. the only place an author
    # runs this at all — demote the author's OWN broken citation to a warning
    # along with the world's. `scan` is what gets read; `changed` is what this
    # commit is answerable for.
    audit = all_citations or bool(os.environ.get("MEMORY_INTEGRITY_ALL_CITATIONS"))
    # A store whose config never mentions citations has opted out, and neither
    # of the two findings below has anything to report about a feature nobody
    # asked for. Both were the first thing a fresh adopter's checker run said.
    declared = store.get("citations_declared", True)
    if declared and not store["cited_roots"]:
        # Say it. With no configured top-level trees the citation regex matches
        # nothing at all, so every memory in the store passes the check without
        # a single path being looked at — a green that means "not configured"
        # and reads as "verified".
        warnings.append(
            f"CITED-PATHS-UNCONFIGURED: {rel_dir} — citations.roots names no "
            "top-level tree, so no prose path citation can match"
        )
    changed, degraded = _changed_files(store["root"], store["blame_base"])
    scan = None if audit else changed
    dead_paths = _check_cited_paths(store, scan)
    for rel, message in dead_paths:
        # World drift NEVER blocks: under --all this run audits memories
        # nobody in this commit touched, so the author it would fail is not
        # the author who broke anything — the surest way to get the whole
        # check switched off. Blame-aligned findings still block, because
        # that is the entire point of having the check.
        if changed is not None and rel in changed:
            errors.append(message)
        else:
            warnings.append(message)

    # A run that checks nothing has to SAY it checks nothing, or it is
    # indistinguishable from a run that passed. Keyed on whether any MEMORY of
    # this store was read, NOT on whether the tree was clean: "clean tree" was
    # the only case named before, so a single unrelated dirty file — a README,
    # a flake.nix — silently put the run back into passing without looking.
    if declared and not audit and not _read_any(store, changed):
        # "none to read" rather than "none changed": a deleted memory IS in the
        # changed set and still lands here, having nothing left to open.
        reason = degraded or f"no {rel_dir}/ memory in the changed set is readable"
        warnings.append(
            f"CITED-PATHS-SKIPPED: {rel_dir} — {reason}; prose path "
            "citations unchecked this run"
        )

    return errors, warnings


def main() -> int:
    # A short user-facing description and a raw formatter, because the module
    # docstring is written for the next maintainer: argparse's default reflow
    # fuses its layout table into a paragraph that parses as nothing, and ships
    # design rationale to whoever typed `--help`.
    ap = argparse.ArgumentParser(
        prog="memory-integrity",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description=(
            "Check a memory store's layout, ledgers, frontmatter and links.\n"
            "\n"
            "Reads the same config the hook does and checks every store it\n"
            "names. Retrieval does not need any of this — a store that fails\n"
            "here is still searched — so run it when you want the ledgers\n"
            "regenerated or the links verified, not to make memkit work.\n"
            "\n"
            "It bootstraps nothing. A store it will pass needs MEMORY.md and\n"
            "SEARCH.md to exist (empty is fine) and both hot/ and search/ to\n"
            "be there; `--write` fills SEARCH.md's rows from your frontmatter\n"
            "and does not create the files."
        ),
        epilog=(
            "exit codes:\n"
            "  0  every store checked out clean (warnings do not fail)\n"
            "  1  a store has errors, or the run could not start — no config,\n"
            "     an unparseable one, or one naming no stores. The first line\n"
            "     of output names which."
        ),
    )
    ap.add_argument(
        "--config",
        metavar="PATH",
        default=None,
        help=f"config file naming the stores to check (default: ${CONFIG_ENV})",
    )
    ap.add_argument(
        "--write",
        action="store_true",
        help="regenerate SEARCH.md, the sub-indexes, and MEMORY.md's counts",
    )
    ap.add_argument(
        "--all",
        action="store_true",
        dest="all_citations",
        help="read prose path citations in EVERY memory, not just the ones "
        "this commit touches; the extra findings are reported as warnings "
        "because drift you did not cause must not fail your commit, while "
        "findings in the memories you DID touch still fail it",
    )
    args = ap.parse_args()

    # Unlike the hook, the checker is not on a prompt's critical path and has
    # no reason to be quiet: no config is a refusal, not an inert pass. It also
    # honours the per-root environment overrides the hook refuses — a checker is
    # a thing an operator points at a tree on purpose.
    try:
        cfg = load_config(args.config, honor_env_overrides=True)
    except ConfigError as exc:
        print(f"memory-integrity: {exc}")
        return 1
    if cfg is None:
        print(
            "memory-integrity: no config — pass --config PATH or set "
            f"${CONFIG_ENV}. There is no default: which trees a checker "
            "verifies is not something to guess at."
        )
        return 1
    stores, notes = stores_from_config(cfg)
    if not stores:
        print(f"memory-integrity: {cfg.path} configures no stores")
        return 1

    all_errors: list[str] = []
    for note in notes:
        print(note)
    # Wikilinks cross stores, so the name index is built once over all of them.
    names = _memory_names(stores)
    for store in stores:
        errors, warnings = check(store, args.write, names, args.all_citations)
        d = store["dir"]
        label = f"{d.relative_to(store['root'])}/"
        n_hot = len(list(store["hot"].glob("*.md"))) if store["hot"].is_dir() else 0
        n_search = (
            len([p for p in store["search"].rglob("*.md") if p.name != "INDEX.md"])
            if store["search"].is_dir()
            else 0
        )
        size = (
            store["hot_ledger"].stat().st_size if store["hot_ledger"].is_file() else 0
        )
        meta = f"{n_hot} hot, {n_search} search, hot ledger {size}b"

        if errors:
            print(f"[FAIL] {label} ({meta})")
            for e in errors:
                print(f"  {e}")
            if any(e.startswith("DEAD-PATH") for e in errors):
                print(f"  {_stale_base_hint(store['blame_base'])}")
            all_errors.extend(errors)
        elif warnings:
            print(f"[WARN] {label} ({meta})")
        else:
            print(f"[OK]   {label} ({meta})")
        for w in warnings:
            print(f"  {w}")
    return 1 if all_errors else 0


def cli() -> None:
    sys.exit(main())


if __name__ == "__main__":
    cli()
